ship_market_addresses = {
    "Pearce X4": {"USDC": "MTc1macY8G2v1MubFxDp4W8cooaSBUZvc2KqaCNwhQE", "ATLAS": "EpqNSh1XWZiCzphHeKE2rqJAEcAtJE8KSBFxnNL4KPDy"},
    "Opal Jet": {"USDC": "2z52mwzBPqA2jGf8jJhCQijHTJ1EUEscX5Mz718SBvmM", "ATLAS": "46m5C7Vy9agesyoE6otKKgeosfzyi1zGcsp4hUvuTH17"},
    "Fimbul Airbike": {"USDC": "", "ATLAS": ""},
    "Fimbul Lowbie": {"USDC": "", "ATLAS": ""},
    "Pearce X5": {"USDC": "3ySaxSspDCsEM53zRTfpyr9s9yfq9yNpZFXSEbvbadLf", "ATLAS": "GNk8Qwff4sHFXA15i5hVLPKWfVPjHsYRcjkUKhbZcD9R"},
    "Opal Jetjet": {"USDC": "2W6ff8LajAwekXVxDARGQ9QFNcRbxmJPE2p3eNsGR7Qu", "ATLAS": "4n8786v44qagL31kyF2VZMZkhoUQkAFpAUTn138wuQyi"},
    "Calico Evac": {"USDC": "2Yu6biqHfnrCKpQThuR9jwC2fJqNzZtKt9jrjo3iKkkc", "ATLAS": ""},
    "Calico Medtech": {"USDC": "", "ATLAS": ""},
    "Calico ATS Enforcer": {"USDC": "", "ATLAS": ""},
    "Pearce R6": {"USDC": "", "ATLAS": ""},
    "VZUS opod": {"USDC": "AT1AoPoFU8WZkW8AnpQsSpUDaRyymvLPvG7k2kGZSwZr", "ATLAS": "G9sJTnHYcyrYkf83U55CCVUPg22pA3CMkZc7MED8uNiU"},
    "Pearce F4": {"USDC": "", "ATLAS": "75qZz971QvKyMMFFPSZfPD2gbgWtX1cTUYH7rfXiEYaC"},
    "Fimbul BYOS Packlite": {"USDC": "BeqGJwPnRb3fJwhSrfhzgUYKqegUtGtvXajTYzEpgGYr", "ATLAS": "CXFcwgehrWq9hXDgt8CmdH9TdbQKnfZveif468ycWeyF"},
    "Calico Compakt Hero": {"USDC": "6ybME9qMbXgLs3PLWvEv8uyL2LWnUZUz7CYGE4m8kEFm", "ATLAS": "8XcMzQptExWMNcuSEjhdyZuFgvi6zz4NS8toQj5fvPjB"},
    "VZUS ambwe": {"USDC": "", "ATLAS": "HcYLMMtf55i1X8pXkEppp6e8n8GKTeJHaGfXdh8AJnte"},
    "Pearce X6": {"USDC": "DLDLMrzumzFSJUub5we5rNTymLtUsnvmRw281pj9wxc9", "ATLAS": ""},
    "Fimbul BYOS Earp": {"USDC": "", "ATLAS": ""},
    "Ogrika Mik": {"USDC": "", "ATLAS": ""},
    "Busan Thrill of Life": {"USDC": "", "ATLAS": ""},
    "Rainbow Om": {"USDC": "", "ATLAS": ""},
    "Fimbul ECOS Greenader": {"USDC": "", "ATLAS": ""},
    "Pearce R8": {"USDC": "", "ATLAS": "4nSVznRaTiQrX4rhVY5KnUC8HPNZh85RsaTbLQZznBMs"},
    "Rainbow Chi": {"USDC": "Giq75C91VWb5cGsLxSRLmzbzAMn7Kvj1yHTy4w2wVhCK", "ATLAS": ""},
    "Tufa Feist": {"USDC": "p6sDGUoCT2wMGsEQ9ZEmw7hdXm3PU539KUL5ouV5GvF", "ATLAS": ""},
    "Fimbul ECOS Unibomba": {"USDC": "", "ATLAS": ""},
    "Rainbow Arc": {"USDC": "", "ATLAS": ""},
    "VZUS ballad": {"USDC": "", "ATLAS": ""},
    "Opal Bitboat": {"USDC": "", "ATLAS": ""},
    "Calico Guardian": {"USDC": "4TpCAobnJfGFRbZ8gAppS9aZBwEGG1k9tRVmx6FPUvUp", "ATLAS": "A8t1VCo6jChYc75882nK1wCc7PSxM2S898ek8sMH45aS"},
    "Ogrika Thripid": {"USDC": "", "ATLAS": ""},
    "Pearce C9": {"USDC": "", "ATLAS": "6SriSyRDGm8tS7f3njPeFEqSu88MsfFjSBzjMdodenqU"},
    "Pearce C11": {"USDC": "D4ciuyvZpcPnaBpdpbRrVN1pKVMgZ8vEgc5PSA1ZbgaH", "ATLAS": "AGeUtKq71xhttwu1PS7uZ7pwXhKXAUFFwiVzYvkzoYaF"},
    "Ogrika Jod Asteris": {"USDC": "27BCSanXrZvkj2z3pj4QNyd3STX4ghVyi4KWvHaM3CAD", "ATLAS": "Ak9fBVwFpm7yit7G8LLcCSXxc7fMXymyJBoH1p9uK28b"},
    "Fimbul ECOS Bombarella": {"USDC": "B9azboFBWzy5VrWbCUoesUTYrBn5VnjDzzpAXTQ9Nu97", "ATLAS": ""},
    "Fimbul ECOS Treearrow": {"USDC": "", "ATLAS": ""},
}